#!/bin/bash

pushd "$(realpath $(dirname $0))"
    ndk-build APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk NDK_PROJECT_PATH=.

    archs="armeabi-v7a arm64-v8a x86 x86_64"
    for arch in $archs ; do
        TARGET_ARCH_ABI=$arch
        if (( $NDK_DEBUG == 1 ))
        then
            rsync -tm \
                --include='*.so' \
                --include='*/' \
                --exclude='*' \
                -r "obj/local/$TARGET_ARCH_ABI" "${SWIFT_PM_EXTERNAL_LIBS}" 
        else
            rsync -tm \
                --include='*.so' \
                --include='*/' \
                --exclude='*' \
                -r "libs/$TARGET_ARCH_ABI" "${SWIFT_PM_EXTERNAL_LIBS}"
        fi
    done
popd