#!/bin/bash

pushd "$(realpath $(dirname $0))"
    ndk-build APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk NDK_PROJECT_PATH=.

    if (( $NDK_DEBUG == 1 ))
    then
        rsync -tm \
            --include='*.so' \
            --include='*/' \
            --exclude='*' \
            -r "obj/local/armeabi-v7a" "${SWIFT_PM_EXTERNAL_LIBS}" 
    else
        rsync -tm \
            --include='*.so' \
            --include='*/' \
            --exclude='*' \
            -r "libs/armeabi-v7a" "${SWIFT_PM_EXTERNAL_LIBS}"
    fi
popd